### PR TITLE
Delete typesense document

### LINKED ISSUE #110: if dropping webpagesummary items in strapi delete the summary from typesense as well

### LINKED ISSUE #111: correct type namings in pothos-graphql
```
type searchWebPages = {
```
is wrong, write
```
type SearchWebPages = {
```

add eslint rule for the future.

### PR DESCRIPTION
**Pull request by TonySchroeder**
close #110

### CODE REVIEW

File: packages/typesense-client/src/delete-document.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+      .documents(id)
+      .delete()
+
+    console.log(`Document ${id} successfully deleted.`)
+  } catch (error) {
+    if (isHttpError(error) && error.httpStatus === 404) {
+      console.log(`Document ${id} does not exist. Skipping deletion.`)
+      return
+    }
+    console.error(`Failed to delete document ${id}`, error)
```
Comment (moncapitaine) [inline packages/typesense-client/src/delete-document.ts:31]:
```suggestion
    console.error(`Failed to delete document ${id}`, error)
    throw error // missing
```

Comment (moncapitaine) [reply packages/typesense-client/src/delete-document.ts:31]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw

File: apps/strapi-cms/src/api/web-page-summary/content-types/web-page-summary/lifecycles.ts [hunk 2]
```diff
@@ -38,4 +39,14 @@ export default {
   async afterUpdate(event) {
     await transformAndUpsertSummary(event.result.id)
   },
+
+  async afterDeleteMany(event) {
+    for (const id of event.params?.where?.$and[0].id.$in) {
+      await deletetDocument(id);
```
Comment (moncapitaine) [inline apps/strapi-cms/src/api/web-page-summary/content-types/web-page-summary/lifecycles.ts:45]: also delete feedback

**Review by moncapitaine — APPROVED** [review]
